### ISSUE TITLE
4.7.2: pytest based test suite  is failing

### ISSUE THREAD

**Issue by kloczek** [sybrenstuvel/python-rsa#180]
I'm not sure is this mypy bug as error message suggest.
Can you have look?
```console
+ /usr/bin/python3 -Bm pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/rsa-4.7.2
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, cov-2.11.1, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, pyfakefs-4.4.0, freezegun-0.4.2, cases-3.4.6, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, flaky-3.7.0, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, hypothesis-6.13.7
collected 97 items

. .                                                                                                                                                                  [  1%]
tests/test_cli.py ..............                                                                                                                                     [ 15%]
tests/test_common.py ...........                                                                                                                                     [ 27%]
tests/test_compat.py ......                                                                                                                                          [ 33%]
tests/test_integers.py ..                                                                                                                                            [ 35%]
tests/test_key.py ......                                                                                                                                             [ 41%]
tests/test_load_save_keys.py ............                                                                                                                            [ 54%]
tests/test_mypy.py F                                                                                                                                                 [ 55%]
tests/test_parallel.py .                                                                                                                                             [ 56%]
tests/test_pem.py .........                                                                                                                                          [ 65%]
tests/test_pkcs1.py .................                                                                                                                                [ 83%]
tests/test_pkcs1_v2.py ...                                                                                                                                           [ 86%]
tests/test_prime.py ....                                                                                                                                             [ 90%]
tests/test_strings.py .                                                                                                                                              [ 91%]
tests/test_transform.py ........                                                                                                                                     [100%]

================================================================================= FAILURES =================================================================================
_______________________________________________________________________ MypyRunnerTest.test_run_mypy _______________________________________________________________________

self = <tests.test_mypy.MypyRunnerTest testMethod=test_run_mypy>

    def test_run_mypy(self):
        proj_root = pathlib.Path(__file__).parent.parent
        args = ['--incremental', '--ignore-missing-imports'] + [str(proj_root / dirname) for dirname
                                                                in test_modules]

        result = mypy.api.run(args)

        stdout, stderr, status = result

        messages = []
        if stderr:
            messages.append(stderr)
        if stdout:
            messages.append(stdout)
        if status:
            messages.append('Mypy failed with status %d' % status)
        if messages and not all('Success' in message for message in messages):
>           self.fail('\n'.join(['Mypy errors:'] + messages))
E           AssertionError: Mypy errors:
E           Mypy failed with status 2

tests/test_mypy.py:27: AssertionError
--------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------
/home/tkloczko/rpmbuild/BUILD/rsa-4.7.2/tests/test_mypy.py:9: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.812
/home/tkloczko/rpmbuild/BUILD/rsa-4.7.2/tests/test_mypy.py:9: : note: please use --show-traceback to print a traceback when reporting a bug
========================================================================= short test summary info ==========================================================================
FAILED tests/test_mypy.py::MypyRunnerTest::test_run_mypy - AssertionError: Mypy errors:
====================================================================== 1 failed, 95 passed in 10.97s =======================================================================
```

**Comment by sybrenstuvel** [comment]
Which version of mypy are you using?

**Comment by kloczek** [comment]
```console
$ pip list | grep mypy
mypy                          0.812
mypy-extensions               0.4.3
```

**Comment by sybrenstuvel** [comment]
It works fine here with mypy 0.800, 0.812, and 0.901, on both Windows 10 and Ubuntu 18.04. I don't think this is a problem with Python-RSA, but seems to be something system-specific.

**Comment by kloczek** [comment]
Hmm after upgrade to 0.901 now I don't see those warnings.
Closing.
